config/routes.rb
StudyDecks::Application.routes.draw do

  resources :decks

  get "session/create"

  get "sessions/create"

  resources :users

  match 'account-created' => 'users#account_created'

  match 'validate_email/:v' => 'users#validate_email'
  match 'users/:id/:message' => 'users#show'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/error/no-access' => 'error#no_access'
  match '/error/email-auth' => 'error#email_auth'
  match '/error/not-signed-in' => 'error#not_signed_in'

  root :to => 'users#new'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  attr_accessible :icon_path, :name, :private
  has_and_belongs_to_many :users
end

app/models/user.rb
require 'base64'
class User < ActiveRecord::Base
	has_secure_password
  attr_accessible :admin, :auth_id, :email, :password, :password_confirmation, :username

  has_and_belongs_to_many :decks

  validates :username, presence: true, length: { maximum: 50 },
            uniqueness: {case_sensitive: false}

  validates :email, presence: true, 
      			uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true


  before_validation :create_auth_id, :on => :create
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  def send_auth_email  user
    params = {"id" => user.id, "auth_id" => user.auth_id}.to_json
    params_encoded = Base64.encode64(params)
    EmailAuthMailer.send_auth_email(user, params_encoded).deliver
  end

  protected

  def create_auth_id
    begin
       self.auth_id = SecureRandom.urlsafe_base64(nil, false)
    end while User.where(auth_id: auth_id).exists?
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :require_signed_in

  # GET /decks
  # GET /decks.json
  def index
    @my_decks = current_user.decks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    @deck = Deck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/new
  # GET /decks/new.json
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:id])
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(params[:deck])
    current_user.decks << @deck

    respond_to do |format|
      if @deck.save
        format.html { redirect_to current_user, notice: 'Deck was successfully created.' }
        format.json { render json: @deck, status: :created, location: @deck }
      else
        format.html { render action: "new" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.json
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def no_access
  end

  def not_signed_in

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    if !params[:session][:email].nil?
      email_param = params[:session][:email].downcase
    else
      email_param = ''
    end
    user = User.find_by_email(email_param)
    if user && user.authenticate(params[:session][:password])
      puts user.inspect
      sign_in user
      redirect_to user
    else
      flash[:error] = 'Invalid email/password combination'
      redirect_to root_url
      # render 'new'
    end
  end

  def destroy 
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
require 'json'

class UsersController < ApplicationController
  before_filter :require_email_auth, :except => [:new, :create, :account_created, :validate_email]
  before_filter :require_same_user, :only => :show
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @message = nil
    if params[:message]
      @message = MESSAGES[params[:message]]
    end

    @user = User.find(params[:id])
    @my_decks = @user.decks
    @public_decks = Deck.includes(:users).where(:private => false).where("users.id != ?", current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.admin = 0;
    respond_to do |format|
      if @user.save
        @user.send_auth_email(@user)
        # format.html { redirect_to '/users/' + @user.id.to_s + '/user_created' }
        format.html { redirect_to '/account-created' }

        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def account_created

  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def validate_email
    url_params = params[:v]
    decoded = JSON.parse(Base64.decode64(url_params))
    @user = User.find(decoded["id"])
    if @user && @user.auth_id == decoded["auth_id"]
      @user.update_attribute(:auth_id, nil)
      sign_in @user
      redirect_to '/users/' + @user.id.to_s + '/email_verified'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def require_signed_in
    if current_user.nil?
      redirect_to '/error/not-signed-in'
      return false
    elsif !current_user.auth_id.nil?  
      redirect_to '/error/email-auth'
      return false
    end 
    return true
  end

  def require_same_user
    redirect_to '/error/no-access' unless params[:id] == current_user.id.to_s
  end

  def require_email_auth
    redirect_to '/error/email-auth' unless current_user.auth_id.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :icon_path %><br />
    <%= f.text_field :icon_path %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>My decks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Icon path</th>
    <th>Private</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @my_decks.each do |deck| %>
  <tr>
    <td><%= deck.name %></td>
    <td><%= deck.icon_path %></td>
    <td><%= deck.private %></td>
    <td><%= link_to 'Show', deck %></td>
    <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
    <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @deck.name %>
</p>

<p>
  <b>Icon path:</b>
  <%= @deck.icon_path %>
</p>

<p>
  <b>Private:</b>
  <%= @deck.private %>
</p>


<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Study Decks</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Create account" %>
  </div>
<% end %>

app/views/users/_header.html.erb
<div class="header">
  <% if signed_in? %>
    <%= link_to "Sign out", signout_path, method: "delete" %>
    <a href="#" class="my-account-trigger">My account</a>   
  <% else %>
    <a href="#" class="login-trigger">Login</a>

    <div class="login-form hidden">
      <%= form_for(:session, url: sessions_path) do |f| %>

          <%= f.label :email %>
          <%= f.text_field :email %>

          <%= f.label :password %>
          <%= f.password_field :password %>

          <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/users/account_created.html.erb
<h1>Account Created! Thanks!</h1>
<p>Please check your email for a confirmation link. Click it and get started!</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="content">
  <%= render 'header' %>

  <div class="new-user">
    <h1>New user? Create an account</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div id="content">
  <%= render 'header' %>
  <!-- <p id="notice"><%= notice %></p> -->

  <% if @message %>
    <div class="message">
      <p><%= @message %></p>
    </div>
  <% end %>

  <h3>My Decks</h3>
  <ul class="my-decks deck-list">
    <% @my_decks.each do |deck| %>
      <li class="deck"><%= deck.name %></li>
    <% end %>
  </ul>

  <h3>Public Decks</h3>
  <ul class="public-decks deck-list">
    <% @public_decks.each do |deck| %>
      <li class="deck"><%= deck.name %></li>
    <% end %>
  </ul>

</div>